spring:
  application:
    name: zuul-gateway

server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
